### ISSUE TITLE
link to download model not working

### ISSUE THREAD

**Issue by m0dB** [clumzy/tag_my_techno#1]
Hi, I would like to try your genre detector, but the link to download your dataset does not work. I get the following (Microsoft
) error:

Something went wrong
This item might have been deleted, expired, or you might not have permission to view it. Contact the owner of this item for more information.

**Comment by clumzy** [comment]
Hello there ! The link must have expired, it should be updated this evening. I'll also try and scrounge up a proper documentation since you're interested :)

**Comment by clumzy** [comment]
@m0dB I've updated the link, and added a short description on how to use the script to try it out yourself :)
FYI this was a student project / demonstrator, so most of it is "quick and dirty", feel free to ask me any questions directly.
Also the genres recognized ATM are the following :
- Acid House
- Acid Techno
- Acid Trance
- Breakbeat House
- Breakbeat Techno
- Deep House
- Detroit House
- Detroit Techno
- Ghetto House
- Hard Techno
- Hard Trance
- Industrial Techno
- Lofi House
- Melodic Techno
- Minimal Deep Tech
- Minimal Techno
- Progressive House
- Progressive Trance
- Psytrance
- Soulful House
- Tech House

**Comment by m0dB** [comment]
Thanks, much appreciated! I have downloaded the file, but I have to leave now. I will give it a try tomorrow and let you know how it goes.

**Comment by clumzy** [comment]
You're welcome, glad to hear it !

**Comment by m0dB** [comment]
I had one missing dependency after installing from requirements.txt: p_tqdm

Unfortunately, for some reason the mdl.keras file is not found, despite having it in the same directory as the `app_playlist_cli.py`:

`ValueError: File not found: filepath=mdl.keras. Please ensure the file is an accessible `.keras` zip file.`

<details><summary>Full output</summary>
<p>

% python3 app_playlist_cli.py --audio_loc ~/Mp3-copy --playlist_loc ~/pls
2024-12-19 21:28:45.057 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-12-19 21:28:45.137 
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run app_playlist_cli.py [ARGUMENTS]
2024-12-19 21:28:45.137 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-12-19 21:28:45.137 
`st.cache` is deprecated and will be removed soon. Please use one of Streamlit's new
caching commands, `st.cache_data` or `st.cache_resource`. More information
[in our docs](https://docs.streamlit.io/develop/concepts/architecture/caching).

**Note**: The behavior of `st.cache` was updated in Streamlit 1.36 to the new caching
logic used by `st.cache_data` and `st.cache_resource`. This might lead to some problems
or unexpected behavior in certain edge cases.

Traceback (most recent call last):
  File "/Users/maarten/git/tag_my_techno/apps/app_playlist_cli.py", line 64, in <module>
    sorter()
  File "/Users/maarten/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/maarten/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/maarten/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/maarten/Library/Python/3.9/lib/python/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/maarten/git/tag_my_techno/apps/app_playlist_cli.py", line 54, in sorter
    model = tmt.create_model(model_loc)
  File "/Users/maarten/Library/Python/3.9/lib/python/site-packages/streamlit/runtime/caching/cache_utils.py", line 218, in __call__
    return self._get_or_create_cached_value(args, kwargs, spinner_message)
  File "/Users/maarten/Library/Python/3.9/lib/python/site-packages/streamlit/runtime/caching/cache_utils.py", line 260, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/Users/maarten/Library/Python/3.9/lib/python/site-packages/streamlit/runtime/caching/cache_utils.py", line 318, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/Users/maarten/git/tag_my_techno/apps/tagmytechno/__init__.py", line 199, in create_model
    my_model = load_model(model_path)
  File "/Users/maarten/Library/Python/3.9/lib/python/site-packages/keras/src/saving/saving_api.py", line 200, in load_model
    raise ValueError(
ValueError: File not found: filepath=mdl.keras. Please ensure the file is an accessible `.keras` zip file.

</p>
</details>

**Comment by clumzy** [comment]
This is likely due to an error with Keras, the version I used for the project is as old as the project itself. Let me check which versions of the modules were in use at the time of the project and I'll edit the requirements file accordingly. 
Should be done by Saturday ! It's a good opportunity to clean up this project (typical case of "it works on my machine" I'm afraid) and ensure it's as _'plug and play'_ as I can, sorry for the hassle and the delay.

**Comment by m0dB** [comment]
No worries! Thanks for looking into this.

**Comment by clumzy** [comment]
Hey, quick update. I'm updating the ETA to a week, with the holidays and all I don't have as much time as I wished to look into the issue and fix it. Thanks for bearing with me :)

**Comment by clumzy** [comment]
@m0dB 
Hello ! I've updated the requirements.txt file with the proper versions for each module, the CLI app worked fine when tested on a new virtual environment using Python 3.10, feel free to try it on your end :)
